backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'fashion'
    label: 'Fashion'
    folder: 'src/content/fashion'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - { label: 'Featured Image', name: 'featured-image', widget: image }
      - label: "Date Font"
        name: "date-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Title Font"
        name: "title-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Budhayanti Script", value: "BudhayantiScript" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: "Subtitle Font"
        name: "subtitle-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - label: "Author Font"
        name: "author-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - label: "Body Font"
        name: "body-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Credits', 
          name: 'credits', 
          widget: 'list',
          field: { label: 'Credit', name: 'credit', widget: 'string' }}
  - name: 'interviews'
    label: 'Interviews'
    folder: 'src/content/interviews'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - { label: 'Featured Image', name: 'featured-image', widget: image }
      - label: "Date Font"
        name: "date-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Title Font"
        name: "title-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Budhayanti Script", value: "BudhayantiScript" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: "Subtitle Font"
        name: "subtitle-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - label: "Author Font"
        name: "author-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: "Body Font"
        name: "body-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Credits', 
          name: 'credits', 
          widget: 'list',
          field: { label: 'Credit', name: 'credit', widget: 'string' }}
  - name: 'lifestyle'
    label: 'Lifestyle'
    folder: 'src/content/lifestyle'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - { label: 'Featured Image', name: 'featured-image', widget: image }
      - label: "Date Font"
        name: "date-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Title Font"
        name: "title-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Budhayanti Script", value: "BudhayantiScript" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: "Subtitle Font"
        name: "subtitle-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - label: "Author Font"
        name: "author-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: "Body Font"
        name: "body-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'bts'
    label: 'BTS'
    folder: 'src/content/bts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - { label: 'Featured Image', name: 'featured-image', widget: image }
      - label: "Date Font"
        name: "date-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Title Font"
        name: "title-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Budhayanti Script", value: "BudhayantiScript" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: "Subtitle Font"
        name: "subtitle-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - label: "Author Font"
        name: "author-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: "Body Font"
        name: "body-font"
        widget: "select"
        options:
          - { label: "Roboto", value: "Roboto" }
          - { label: "The Light Font", value: "TheLightFont" }
          - { label: "Slabo", value: "Slabo" }
          - { label: "Pixeland", value: "Pixeland" }
          - { label: "Iowan Old Style", value: "IowanOldStyle" }
          - { label: "Futurist", value: "Futurist" }
          - { label: "Avenir Next Pro", value: "AvenirNextPro" }
          - { label: "Andale Mono", value: "AndaleMono" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Credits', 
          name: 'credits', 
          widget: 'list',
          field: { label: 'Credit', name: 'credit', widget: 'string' }}
  - name: "pages"
  - label: "Pages"
  files:
    - file: "src/content/shop.md"
      label: "Shop"
      name: "shop"
      fields: 
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shop-page"}
        - {label: "Cover Image", name: "coverImage", widget: "image"}
        - {label: "Price", name: "price", widget: "string"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Details", name: "details", widget: "text"}
        - label: "Gallery"
          name: "galleryImages"
          widget: "list"
          field: {label: Image, name: image, widget: image}
